### ISSUE TITLE
Can I use gbx-net to generate maps?

### ISSUE THREAD

**Issue by NicEastvillage** [BigBang1112/gbx-net#113]
Hi there. I was wondering if I could gbx-net to generate a TM2020 map? E.g. given a pool of blocks, build a map with them according to some algorithm.

I see that I can read maps and get basic info about the map and its blocks, but I can't see how I would create a new blank map and populate it with blocks. Once I know how to create a valid map with blocks in it I will be good to go.

I tried this, but I can't open the resulting map ingame.

```cs
var map = new CGameCtnChallenge();
map.MapName = "Test123";
map.Blocks = new List<CGameCtnBlock>() { someOtherMap.Blocks[new Random().Next(someOtherMap.Blocks.Count)] };
map.Save("Output.Map.Gbx");
```

Can someone point me in the right direction?

**Comment by BigBang1112** [comment]
Template map works and is the simplest option currently.

When you hover over the `CGameCtnChallenge` constructor, you'll see a message that's on every `Engines` class constructor:

```
Creates a new instance of CGameCtnChallenge with no chunks inside (no data will be serialized).
```

> There's only a small exception of this rule and that is `CGameCtnBlock` which has this description too but it doesn't really apply to it.

You need to add appropriate data chunk definitions to the map using `map.CreateChunk<CGameCtnChallenge.Chunk03043XXX>()` or `map.Chunks.Create<CGameCtnChallenge.Chunk03043XXX>()`. To view which chunks are necessary, you can either use https://explorer.gbx.tools/ or print out `Id` of each element in `map.Chunks`. It can be pretty tedious in the case of maps though so using a template map is definitely simpler.

Also small note, `DeepClone` is currently not working properly. You also don't need to deep clone to repeat the objects. Only if you want to reuse blocks but with a different property of each like name, due to the mutable nature, you have to duplicate the objects.

**Comment by NicEastvillage** [comment]
I see. Yeah, I will stick to using a template for now then. Thanks!
